title: Evan Aalami
logo: /assets/img/Headshot.png
description: Versatile full-stack Game Developer with agile and leadership experience.
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-the
show_downloads: false
